features/support/app/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :sessions
  map.resources :pepinos
  map.resources :tomatoes
  map.resources :chards
  map.resources :terraces
  map.resources :crops
  map.resources :fertilizers
  map.resources :orchards
  map.resources :deliveries
  map.resources :flowers
  map.resources :users

  map.root :controller => "welcome"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

features/support/app/app/models/chard.rb
class Chard < ActiveRecord::Base
  belongs_to :terrace
end

features/support/app/app/models/crop.rb
class Crop < ActiveRecord::Base
  has_many :terraces
  has_many :sprinklers, :as => :sprinklerable
end

features/support/app/app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :user
  belongs_to :flower
end

features/support/app/app/models/fertilizer.rb
class Fertilizer < ActiveRecord::Base
end

features/support/app/app/models/flower.rb
class Flower < ActiveRecord::Base
  belongs_to :from, :class_name => 'User'
  has_many :deliveries
  has_many :users, :through => :deliveries
end

features/support/app/app/models/lettuce.rb
class Lettuce < ActiveRecord::Base
  belongs_to :orchard_of_birth, :class_name => 'Orchard'
end

features/support/app/app/models/orchard.rb
class Orchard < ActiveRecord::Base
  belongs_to :fertilizer
  has_many :terraces
  accepts_nested_attributes_for :terraces, :allow_destroy => true, :reject_if => proc { |attrs| attrs.all? {|k,v| v.blank?} }

  has_many :crops, :through => :terraces
  has_many :sprinklers, :as => :sprinklerable

  def watering_time(type)
    if sw = self.send("#{type}_watering")
      format("%d:%02d", sw.hour, sw.min)
    else
      '--:--'
    end
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

features/support/app/app/models/pepino.rb
class Pepino < ActiveRecord::Base
  belongs_to :terrace
end

features/support/app/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

features/support/app/app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id
  attr_protected :user_id

  attr_accessor :name, :password

  def before_validation
    self.user = User.find_by_name_and_password(name, password)
  end
end

features/support/app/app/models/sprinkler.rb
class Sprinkler < ActiveRecord::Base
  belongs_to :sprinklerable, :polymorphic => true
end

features/support/app/app/models/terrace.rb
class Terrace < ActiveRecord::Base
  belongs_to :orchard
  belongs_to :crop
  has_many   :chards
  has_many   :tomatoes
  has_many   :cucumbers, :class_name => 'Pepino'
end

features/support/app/app/models/tomato.rb
class Tomato < ActiveRecord::Base
  belongs_to :terrace
end

features/support/app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :sended_flowers, :class_name => 'Flower', :foreign_key => 'from_id'
  has_many :deliveries
  has_many :flowers, :through => :deliveries
  has_one  :profile
end

features/support/app/app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => '89804438ed16902b08d2cca29950229f'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

features/support/app/app/controllers/chards_controller.rb
class ChardsController < ApplicationController
end

features/support/app/app/controllers/crops_controller.rb
class CropsController < ApplicationController
end

features/support/app/app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_filter :session_required, :except => [:show, :index]
  # GET /flowers
  # GET /flowers.xml
  def index
    @flowers = Flower.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flowers }
    end
  end

  # GET /flowers/1
  # GET /flowers/1.xml
  def show
    @flower = Flower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @flower }
    end
  end

  # GET /flowers/new
  # GET /flowers/new.xml
  def new
    @flower = Flower.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flower }
    end
  end

  # GET /flowers/1/edit
  def edit
    @flower = Flower.find(params[:id])
  end

  # POST /flowers
  # POST /flowers.xml
  def create
    @flower = Flower.new(params[:flower])
    @flower.from_id = session[:id]
    respond_to do |format|
      if @flower.save
        flash[:notice] = t('flower.created')
        format.html { redirect_to(@flower) }
        format.xml  { render :xml => @flower, :status => :created, :location => @flower }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @flower.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flowers/1
  # PUT /flowers/1.xml
  def update
    @flower = Flower.find(params[:id])

    respond_to do |format|
      if @flower.update_attributes(params[:flower])
        flash[:notice] = 'Flower was successfully updated.'
        format.html { redirect_to(@flower) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flower.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.xml
  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy

    respond_to do |format|
      format.html { redirect_to(flowers_url) }
      format.xml  { head :ok }
    end
  end
  private
    def session_required
      if session[:id].nil?
        flash[:alert] = "Please, login first"
        redirect_to new_session_path
      end
    end
end

features/support/app/app/controllers/orchards_controller.rb
class OrchardsController < ApplicationController
  def index
    @orchards = Orchard.find(:all, :order => :id)
  end      

  def show
    @orchard = Orchard.find(params[:id][/^(\d+)-.*$/, 1])
  end

  def edit
    @orchard = Orchard.find(params[:id][/^(\d+)-.*$/, 1])
  end

  def new
    @orchard = Orchard.new
  end

  def create
    @orchard = Orchard.new(params[:orchard])
    if @orchard.save
      flash[:notice] = 'The orchard was successfully created.'
      redirect_to @orchard
    else
      render :action => "new"
    end
  end

  def update
    @orchard = Orchard.find(params[:id])
    if @orchard.update_attributes(params[:orchard])
      flash[:notice] = 'Orchard was successfully updated.'
      redirect_to @orchard
    else
      render :action => "edit"
    end
  end

  def destroy
    @orchard = Orchard.find(params[:id])
    @orchard.destroy
    redirect_to(orchards_url) 
  end
end

features/support/app/app/controllers/pepinos_controller.rb
class PepinosController < ApplicationController
end

features/support/app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

features/support/app/app/helpers/application_helper.rb
module ApplicationHelper
  def setup_orchard(orchard)
    returning orchard do |o|
      o.terraces.build
    end
  end
end

features/support/app/app/views/flowers/new.html.erb
<h1>New flower</h1>

<% form_for(@flower) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :file_path %><br />
    <%= f.text_field :file_path %>
  </p>
  <p>
  <ul>
  <% User.find(:all, :conditions => ['id <> ?', session[:id]]).each do |user| %>
    <li>
      <input id="flower_user_ids_<%= user.id %>"  type="checkbox" name="flower[user_ids][]" value="<%= user.id %>" />
      <label for="flower_user_ids_<%= user.id %>"><%= user.name %></label>
    </li> 
  <% end %>
  </ul>
  </p>
  <p>
    <%= f.submit 'Enviar' %>
  </p>
<% end %>

<%= link_to 'Back', flowers_path %>

features/support/app/app/views/flowers/show.html.erb
<p><%= flash[:notice] %></p>
<p>
  <b>Title:</b>
  <%=h @flower.title %>
</p>

<p>
  <b>From:</b>
  <%=h @flower.from_id %>
</p>

<p>
  <b>File path:</b>
  <%=h @flower.file_path %>
</p>


<%= link_to 'Edit', edit_flower_path(@flower) %> |
<%= link_to 'Back', flowers_path %>

features/support/app/app/views/orchards/_form.html.erb
<% form_for setup_orchard(@orchard) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name, "Nombre" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :area, "Área" %><br />
    <%= f.text_field :area %>
  </p>
  <p>
    <%= f.label :longitude, "Longitud" %><br />
    <%= f.text_field :longitude %>
  </p>
  <p>
    <%= f.label :latitude, "Latitud" %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :start_watering, 'Comienzo de riego' %><br />
    <%= f.time_select :start_watering %>
  </p>
  <p>
    <%= f.label :stop_watering, 'Finalización de riego' %><br />
    <%= f.time_select :stop_watering %>
  </p>

  <h3>Bancales</h3>
  <% f.fields_for :terraces do |terrace_form| %>
    <p>
    <% if terrace_form.object.new_record? %>
    <%= terrace_form.label :name, 'Nuevo bancal' %>
    <%= terrace_form.text_field :name %>
    <% else %>
    <%= terrace_form.label :name, "Bancal #{terrace_form.object.name}" %>
    <%= terrace_form.text_field :name %>
    <%= terrace_form.check_box :_destroy %>
    <%= terrace_form.label :_destroy, 'Borrar' %>
    <% end %>
    </p> 
  <% end %>

  <p>
    <%= f.submit(params[:action] == 'new' ? "Crear" : "Guardar") %>
  </p>
<% end %>

<%= link_to 'Página de Huertos', orchards_path %>

features/support/app/app/views/orchards/edit.html.erb
<h2>Edición de Huerta</h2>

<%= render :partial => 'form' %>

features/support/app/app/views/orchards/index.html.erb
<h1>Listado de Huertos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Área</th>
    <th>Longitud</th>
    <th>Latitud</th>
  </tr>

<% for orchard in @orchards %>
  <tr>
    <td><%=h orchard.name %></td>
    <td><%=h orchard.area %></td>
    <td><%=h orchard.longitude %></td>
    <td><%=h orchard.latitude %></td>
    <td><%= link_to 'Ver', orchard %></td>
    <td><%= link_to 'Editar', edit_orchard_path(orchard) %></td>
    <td><%= link_to 'Borrar', orchard, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New orchard', new_orchard_path %>

features/support/app/app/views/orchards/new.html.erb
<h2>Alta de Huerta</h2>

<%= render :partial => 'form' %>

features/support/app/app/views/orchards/show.html.erb
<h1>Página de huerto</h1> <h2><%= @orchard.name %></h2>
<p>
  <b>Área:</b>
  <%=h @orchard.area %>
</p>

<p>
  <b>Longitud:</b>
  <%=h @orchard.longitude %>
</p>

<p>
  <b>Latitud:</b>
  <%=h @orchard.latitude %>
</p>


<p>
  <b>Riego:</b>
  De <span id="riego-comienzo"><%= @orchard.watering_time :start %></span>
  a <span id="riego-fin"><%= @orchard.watering_time :stop %></span>
</p>
<% if @orchard.terraces.any? %>
  <div id="terraces">  
    <b>Bancales:</b>
    <ul>
  <% @orchard.terraces.each do |terrace| %>
      <li><%= terrace.name %></li>  
  <% end %>
    </ul>
  </div>  
<% end %>

<%= link_to 'Editar', edit_orchard_path(@orchard) %> |
<%= link_to 'Página de Huertos', orchards_path %>